sudo: false
language: cpp
compiler:
 - gcc
 - clang
arch: 
    - amd64
    - ppc64le
addons:
 apt:
  packages:
   - libusb-1.0-0-dev
   - libjpeg-dev
before_script:
 - mkdir build
 - cd build
 - cmake ..
script:
 - make
